spring:
  application:
    name: hxBI

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.134:3306/bi
    username: root
    password: root

  redis:
    # Redis服务器连接端口
    host: 192.168.159.134
    # Redis数据库索引（默认为0）
    database: 1
    port: 6379
    # 连接超时时间
    timeout: 5s
    password: adorabled4
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  rabbitmq:
    host: 192.168.159.134
    port: 5672
    username: dhx
    password: qwer
    virtual-host: /
server:
  port: 6848
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0 # mybatis-plus 逻辑删除
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql


knife4j:
  enable: true
  openapi:
    title: hxBI_bankend
    description: 后端接口文档
    email: dhx2648466390@163.com
    concat: adorabled4
    url: https://blog.dhx.icu
    version: v4.0
    license: Apache 2.0
    license-url: https://blog.dhx.icu
    terms-of-service-url: https://blog.dhx.icu
    group:
      dev:
        group-name: 开发环境
        api-rule: package
        api-rule-resources:
          - com.dhx.bi.controller

logging:
  config: classpath:logback.xml # 日志配置文件

template:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
yuapi:
  client:
    access-key: 3s4a0scf557tvxndeup21unetan7ly1j
    secret-key: q83o1vnlpd8urm3ha1g15r6tm3t701rp