spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.79.173:4234/bi?useUnicode=true&characterEncoding=utf-8&useSSL=true&&serverTimezone=Asia/Shanghai
    username: root
    password: adorabled4
  redis:
    # Redis服务器连接端口
    host: 8.130.79.173
    # Redis数据库索引（默认为0）
    database: 1
    port: 6379
    # 连接超时时间
    timeout: 5s
    password: r324fhh2n3084brj2w
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  rabbitmq:
    host: 8.130.79.173
    port: 5672
    username: dhx
    password: r324fhh2n3084brj2w
    virtual-host: /
  data:
    mongodb:
      host: 8.130.79.173
      port: 27017
      database: bi
      username: root
      password: root