spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.79.173:3306/bi
    username: root
    password: r324fhh2n3084brj2w

  redis:
    # Redis服务器连接端口
    host: 8.130.79.173
    # Redis数据库索引（默认为0）
    database: 1
    port: 6379
    # 连接超时时间
    timeout: 5s
    password: r324fhh2n3084brj2w
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

template:
  thread:
    core-size: 4
    max-size: 8
    keep-alive-time: 10
yuapi:
  client:
    access-key: 3s4a0scf557tvxndeup21unetan7ly1j
    secret-key: q83o1vnlpd8urm3ha1g15r6tm3t701rp