name: hxbi-backend-DockerImageCI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  bt-product-release:
    if: ${{ github.ref == 'refs/heads/master' }}  # 检测master分支是否有更新
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # pull代码到运行服务器上
    # set up JDK
    - name: Set up JDK 8.0.382
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.382'
        distribution: 'temurin'
        cache: maven
    # log
    - name: Show Directory and Files
      run: |
        pwd
        ls -la
    # build jar
    - name: Build with Maven # build jar 
      run: mvn -B package -DskipTests --file pom.xml
      
    # login to ACR
    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
      with:
        login-server: registry.cn-wulanchabu.aliyuncs.com # 务必正确填写镜像容器服务的登录地址
        region-id: lietu_hxbi/hxbi # 务必正确填写镜像容器服务的登录地址
        username: "${{ secrets.REGISTRY_USERNAME }}" # 引用GitHub repo设置的镜像容器服务用户名
        password: "${{ secrets.REGISTRY_PASSWORD }}" # 引用GitHub repo设置的镜像容器服务密码
        
    # build image and push to ACR
    - name: Build and Push Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }} # 用于标记容器版本号
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/lietu_hxbi/hxbi:$IMAGE_TAG .
        docker push registry.cn-hangzhou.aliyuncs.com/lietu_hxbi/hxbi:$IMAGE_TAG
